apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-moouxztz
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-moouxztz:18ded52ed70c4f9dfc08a2d5c79ac152a03d1a7e@sha256:7c9951e042e66b4fe7855b08508c6588a85964e969a4b6179517350799fe72a6
          name: container-image
